/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coordinate { 'latitude' : number, 'longitude' : number }
export interface FavoritePlace {
  'owner' : [] | [Principal],
  'name' : string,
  'placeId' : string,
}
export interface SearchEntry {
  'term' : string,
  'timestamp' : Time,
  'coordinates' : Coordinate,
  'zoomLevel' : bigint,
}
export interface SearchEntryInternal {
  'owner' : [] | [Principal],
  'term' : string,
  'timestamp' : Time,
  'coordinates' : Coordinate,
  'zoomLevel' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  '__favoritePlaces' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, FavoritePlace]>
  >,
  '__searchHistory' : ActorMethod<
    [[] | [string], [] | [bigint]],
    Array<[string, SearchEntryInternal]>
  >,
  'addFavoritePlace' : ActorMethod<[string, string], undefined>,
  'addSearchTerm' : ActorMethod<[string, number, number, bigint], undefined>,
  'clearSearchHistory' : ActorMethod<[], undefined>,
  'getFavoritePlaces' : ActorMethod<[], Array<[string, string]>>,
  'getSearchHistory' : ActorMethod<[], Array<[string, SearchEntry]>>,
  'removeFavoritePlace' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];