/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FavoritePlace = IDL.Record({
  'owner' : IDL.Opt(IDL.Principal),
  'name' : IDL.Text,
  'placeId' : IDL.Text,
});
export const Time = IDL.Int;
export const Coordinate = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const SearchEntryInternal = IDL.Record({
  'owner' : IDL.Opt(IDL.Principal),
  'term' : IDL.Text,
  'timestamp' : Time,
  'coordinates' : Coordinate,
  'zoomLevel' : IDL.Int,
});
export const SearchEntry = IDL.Record({
  'term' : IDL.Text,
  'timestamp' : Time,
  'coordinates' : Coordinate,
  'zoomLevel' : IDL.Int,
});

export const idlService = IDL.Service({
  '__favoritePlaces' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, FavoritePlace))],
      ['query'],
    ),
  '__searchHistory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(IDL.Text, SearchEntryInternal))],
      ['query'],
    ),
  'addFavoritePlace' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addSearchTerm' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int],
      [],
      [],
    ),
  'clearSearchHistory' : IDL.Func([], [], []),
  'getFavoritePlaces' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getSearchHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, SearchEntry))],
      ['query'],
    ),
  'removeFavoritePlace' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FavoritePlace = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'name' : IDL.Text,
    'placeId' : IDL.Text,
  });
  const Time = IDL.Int;
  const Coordinate = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const SearchEntryInternal = IDL.Record({
    'owner' : IDL.Opt(IDL.Principal),
    'term' : IDL.Text,
    'timestamp' : Time,
    'coordinates' : Coordinate,
    'zoomLevel' : IDL.Int,
  });
  const SearchEntry = IDL.Record({
    'term' : IDL.Text,
    'timestamp' : Time,
    'coordinates' : Coordinate,
    'zoomLevel' : IDL.Int,
  });
  
  return IDL.Service({
    '__favoritePlaces' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, FavoritePlace))],
        ['query'],
      ),
    '__searchHistory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(IDL.Text, SearchEntryInternal))],
        ['query'],
      ),
    'addFavoritePlace' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addSearchTerm' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Int],
        [],
        [],
      ),
    'clearSearchHistory' : IDL.Func([], [], []),
    'getFavoritePlaces' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getSearchHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, SearchEntry))],
        ['query'],
      ),
    'removeFavoritePlace' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };