/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchEntryInternal {
    owner?: Principal;
    term: string;
    timestamp: Time;
    coordinates: Coordinate;
    zoomLevel: bigint;
}
export interface FavoritePlace {
    owner?: Principal;
    name: string;
    placeId: string;
}
export interface SearchEntry {
    term: string;
    timestamp: Time;
    coordinates: Coordinate;
    zoomLevel: bigint;
}
export type Time = bigint;
export interface Coordinate {
    latitude: number;
    longitude: number;
}
export interface backendInterface {
    __favoritePlaces(ko: string | null, count: bigint | null): Promise<Array<[string, FavoritePlace]>>;
    __searchHistory(ko: string | null, count: bigint | null): Promise<Array<[string, SearchEntryInternal]>>;
    addFavoritePlace(placeId: string, name: string): Promise<void>;
    addSearchTerm(term: string, lat: number, long: number, zoom: bigint): Promise<void>;
    clearSearchHistory(): Promise<void>;
    getFavoritePlaces(): Promise<Array<[string, string]>>;
    getSearchHistory(): Promise<Array<[string, SearchEntry]>>;
    removeFavoritePlace(placeId: string): Promise<void>;
}
import type { Coordinate as _Coordinate, FavoritePlace as _FavoritePlace, SearchEntryInternal as _SearchEntryInternal, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __favoritePlaces(arg0: string | null, arg1: bigint | null): Promise<Array<[string, FavoritePlace]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__favoritePlaces(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__favoritePlaces(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __searchHistory(arg0: string | null, arg1: bigint | null): Promise<Array<[string, SearchEntryInternal]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__searchHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__searchHistory(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addFavoritePlace(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoritePlace(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoritePlace(arg0, arg1);
            return result;
        }
    }
    async addSearchTerm(arg0: string, arg1: number, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSearchTerm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSearchTerm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async clearSearchHistory(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearSearchHistory();
            return result;
        }
    }
    async getFavoritePlaces(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavoritePlaces();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavoritePlaces();
            return result;
        }
    }
    async getSearchHistory(): Promise<Array<[string, SearchEntry]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchHistory();
            return result;
        }
    }
    async removeFavoritePlace(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavoritePlace(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavoritePlace(arg0);
            return result;
        }
    }
}
function from_candid_FavoritePlace_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FavoritePlace): FavoritePlace {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_SearchEntryInternal_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchEntryInternal): SearchEntryInternal {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: [] | [Principal];
    term: string;
    timestamp: _Time;
    coordinates: _Coordinate;
    zoomLevel: bigint;
}): {
    owner?: Principal;
    term: string;
    timestamp: Time;
    coordinates: Coordinate;
    zoomLevel: bigint;
} {
    return {
        owner: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.owner)),
        term: value.term,
        timestamp: value.timestamp,
        coordinates: value.coordinates,
        zoomLevel: value.zoomLevel
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: [] | [Principal];
    name: string;
    placeId: string;
}): {
    owner?: Principal;
    name: string;
    placeId: string;
} {
    return {
        owner: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.owner)),
        name: value.name,
        placeId: value.placeId
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _FavoritePlace]): [string, FavoritePlace] {
    return [
        value[0],
        from_candid_FavoritePlace_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _SearchEntryInternal]): [string, SearchEntryInternal] {
    return [
        value[0],
        from_candid_SearchEntryInternal_n10(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _FavoritePlace]>): Array<[string, FavoritePlace]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _SearchEntryInternal]>): Array<[string, SearchEntryInternal]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
